name: Publish NuGet package

on:
  push:
    tags:
      - 'v*'

jobs:
  deployment:

    runs-on: ubuntu-latest
    name: Publish NuGet package
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100

    - name: Create NuGet package
      run: dotnet pack -property:Configuration=Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Push Nuget Package to nuget.org
      run: dotnet nuget push *\**.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
