name: Run tests

on:
  push:
    branches:
      - '*'

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        dotnet: [ 3.0.100, 3.1.100 ]

    name: .NET Core SDK ${{ matrix.dotnet }} on ${{ matrix.os }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: ${{ matrix.dotnet }}

    - name: Building project
      run: dotnet build ./YourAwesomeProject/

    - name: Running tests
      run: dotnet test ./YourAwesomeProject.Tests/
